# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 561893c969edbf7b0bdcce13f06cd6275903dba6bb36061e0f4908cc2f4387f594fbd5dd3bddcf73e6933df6b8c3e5ae8df6ac77e9ae6dafdc11ea26200ed5c5

test:
  secret_key_base: be1ae7a3356803cb1400bbc801f6ccb4c498034e339bb6f3c38bcde93c353c268be73051087f1961114f099a51ada75b650d64c1e9e2970e78454b7fb433a4d8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
